version: '3.7'

services:
  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MAGISHIFT_MONGO_DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MAGISHIFT_MONGO_DB_PASSWORD}
      MONGO_INITDB_DATABASE: ${MAGISHIFT_MONGO_DB_NAME}
    ports:
      - ${MAGISHIFT_MONGO_DB_PORT}:27017
    command:
      - --storageEngine=wiredTiger

  mongo-express:
    image: mongo-express
    depends_on:
      - 'mongo'
    ports:
      - ${MAGISHIFT_MONGO_EXPRESS_PORT}:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MAGISHIFT_MONGO_DB_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MAGISHIFT_MONGO_DB_PASSWORD}

  postgres:
    image: postgres:9.6.6
    environment:
      POSTGRES_PASSWORD: ${MAGISHIFT_DB_PASSWORD}
      POSTGRES_USER: ${MAGISHIFT_DB_USER}
      POSTGRES_DB: ${MAGISHIFT_DB_NAME}
    ports:
      - ${MAGISHIFT_DB_PORT}:5432

  redis:
    image: redis:latest
    hostname: redis
    ports:
      - ${MAGISHIFT_REDIS_PORT}:6379

  redis-commander:
    image: rediscommander/redis-commander:latest
    depends_on:
      - 'redis'
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - ${MAGISHIFT_REDIS_COMMANDER_PORT}:8081

  adminer:
    image: adminer
    depends_on:
      - postgres
    ports:
      - ${MAGISHIFT_ADMINER_PORT}:8080
    depends_on:
      - 'postgres'

  grafana:
    image: grafana/grafana:latest
    ports:
      - ${MAGISHIFT_GRAFANA_PORT}:3000
    environment:
      - GF_INSTALL_PLUGINS=grafana-clock-panel,briangann-gauge-panel,natel-plotly-panel
    depends_on:
      - 'postgres'
