version: '3.7'

services:
  postgres:
    image: postgres:latest
    volumes:
      - ./docker-postgres-init:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD: ${MAGISHIFT_DB_PASSWORD}
      POSTGRES_USER: ${MAGISHIFT_DB_USER}
      POSTGRES_MULTIPLE_DATABASES: ${MAGISHIFT_DB_NAME}, ${KEYCLOAK_DB_NAME}
    ports:
      - ${MAGISHIFT_DB_PORT}:5432

  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MAGISHIFT_MONGO_DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MAGISHIFT_MONGO_DB_PASSWORD}
      MONGO_INITDB_DATABASE: ${MAGISHIFT_MONGO_DB_NAME}
    ports:
      - ${MAGISHIFT_MONGO_DB_PORT}:27017
    command:
      - --storageEngine=wiredTiger

  mongo-express:
    image: mongo-express
    depends_on:
      - 'mongo'
    ports:
      - ${MAGISHIFT_MONGO_EXPRESS_PORT}:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MAGISHIFT_MONGO_DB_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MAGISHIFT_MONGO_DB_PASSWORD}

  redis:
    image: redis:latest
    hostname: redis
    ports:
      - ${MAGISHIFT_REDIS_PORT}:6379

  redis-commander:
    image: rediscommander/redis-commander:latest
    depends_on:
      - 'redis'
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - ${MAGISHIFT_REDIS_COMMANDER_PORT}:8081

  adminer:
    image: adminer
    depends_on:
      - postgres
    ports:
      - ${MAGISHIFT_ADMINER_PORT}:8080
    depends_on:
      - 'postgres'

  grafana:
    image: grafana/grafana:latest
    ports:
      - ${MAGISHIFT_GRAFANA_PORT}:3000
    environment:
      - GF_INSTALL_PLUGINS=grafana-clock-panel,briangann-gauge-panel,natel-plotly-panel
    depends_on:
      - 'postgres'

  keycloak:
    image: jboss/keycloak
    links:
      - maildev
    volumes:
      - ./keycloak/magishift/:/opt/jboss/keycloak/themes/magishift/
      - ./keycloak/magishift-internal/:/opt/jboss/keycloak/themes/magishift-internal/
      - ./keycloak/magishift-social-providers/:/opt/jboss/keycloak/themes/magishift-social-providers/
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: ${KEYCLOAK_DB_NAME}
      DB_USER: ${MAGISHIFT_DB_USER}
      DB_PASSWORD: ${MAGISHIFT_DB_PASSWORD}
      KEYCLOAK_USER: ${KEYCLOAK_USER}
      KEYCLOAK_PASSWORD: ${KEYCLOAK_PASSWORD}
    ports:
      - ${KEYCLOAK_PORT}:8080
    depends_on:
      - postgres

  ldap-host:
    image: osixia/openldap
    environment:
      - LDAP_ORGANISATION=${LDAP_ORGANISATION}
      - LDAP_DOMAIN=${LDAP_DOMAIN}
    ports:
      - ${LDAP_PORT}:389

  phpldapadmin-service:
    image: osixia/phpldapadmin
    environment:
      - PHPLDAPADMIN_LDAP_HOSTS=ldap-host
    ports:
      - ${LDAP_PHPLDAPADMIN_PORT}:443
    depends_on:
      - ldap-host

  maildev:
    image: djfarrelly/maildev
    ports:
    - "${MAILDEV_PORT}:80"
    - "25"