/**
 * @file Automatically generated by barrelsby.
 */

export * from './base.controller';
export * from './base.dto';
export * from './base.entity';
export * from './base.resolver';
export * from './base.service';
export * from './interfaces/base.interface';
export * from './interfaces/baseMapper.Interface';
