version: '3.7'

services:
  postgres:
    image: postgres:latest
    volumes:
      - ./docker-postgres-init:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD: ${TYPEORM_PASSWORD}
      POSTGRES_USER: ${TYPEORM_USERNAME}
      POSTGRES_MULTIPLE_DATABASES: ${TYPEORM_DATABASE}, ${KEYCLOAK_DB_NAME}
    ports:
      - ${TYPEORM_PORT}:5432

  keycloak:
    image: jboss/keycloak
    volumes:
      - ./keycloak/magishift/:/opt/jboss/keycloak/themes/magishift/
      - ./keycloak/magishift-internal/:/opt/jboss/keycloak/themes/magishift-internal/
      - ./keycloak/magishift-social-providers/:/opt/jboss/keycloak/themes/magishift-social-providers/
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: ${KEYCLOAK_DB_NAME}
      DB_USER: ${TYPEORM_USERNAME}
      DB_PASSWORD: ${TYPEORM_PASSWORD}
      KEYCLOAK_USER: ${KEYCLOAK_USER_MASTER}
      KEYCLOAK_PASSWORD: ${KEYCLOAK_PASSWORD_MASTER}
    ports:
      - ${KEYCLOAK_PORT}:8080
    depends_on:
      - postgres

  redis:
    image: redis:latest
    hostname: redis
    ports:
      - ${REDIS_PORT}:6379