service:
  name: magishift-keycloak-service

provider:
  name: aws
  runtime: nodejs8.10
  region: 'ap-southeast-1'
  stage: ${opt:stage, 'dev'}

plugins:
  - '@hewmen/serverless-plugin-typescript'
  - serverless-plugin-optimize
  - serverless-offline
  - serverless-dotenv-plugin

package:
  exclude:
    - .git/**
    - dist/**
    - src/**
    - test/**
    - nodemon.json
    - README.md
  individually: true

functions:
  main:
    handler: src/handler.handler
    events:
      - http:
          cors: true
          method: any
          path: /{proxy+}