service:
  name: magishift-keycloak-service

provider:
  name: aws
  runtime: nodejs8.10
  region: 'ap-southeast-1'

plugins:
  - '@hewmen/serverless-plugin-typescript'
  - serverless-plugin-optimize
  - serverless-offline

package:
  exclude:
    - .git/**
    - dist/**
    - src/**
    - test/**
    - nodemon.json
    - README.md
    - .env*
  individually: true

functions:
  main:
    handler: src/aws-lambda/handler.handler
    events:
      - http:
          cors: true
          method: any
          path: /{proxy+}